### ISSUE TITLE
Consider auto-building via GitHub actions

### ISSUE THREAD

**Issue by hinerm** [Rocsg/FijiRelax#10]
**Is your feature request related to a problem? Please describe.**
It is nice to know when your commits break your code, so having some sort of continuous integration is always preferable. 

**Describe the solution you'd like**
Create a minimal GitHub Action to run the Maven build after each commit to the main brain.

**Describe alternatives you've considered**
There are other continuous integration options but GH Actions are well-integrated and fairly straightforward to set up.

**Additional context**
This should come after [fixing the unit tests](https://github.com/Rocsg/FijiRelax/issues/9).

Start with the [Building and testing Java with Maven](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven) documentation and adapt the YAML as needed.

Optionally:
- Add a step to grab (e.g. curl) the platform-appropriate `SimpleITKJava` native lib from [the ImageJ-ITK update site](https://sites.imagej.net/ImageJ-ITK/lib/)
- Note that you can use the `setup-java` action to [cache maven dependencies](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven#caching-dependencies)
- Use the [GitHub actions cache](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) to cache he `SimpleITKJava` native library

**Comment by Rocsg** [comment]
Hello @hinerm ,
I wish you a fresh and cool new year, with what you want in it.

I think I struggled to setup curl grabbing, and caching dependancies, until the test with registration finally starts and execute well. That is really nice, I bet I could setup such tests for Fijiyama, too.

For the native library, I struggled until it worked, and finished with it in my pom:

	          <artifactId>maven-surefire-plugin</artifactId>
              <configuration>
                  <argLine>-Djava.library.path=${java.library.path};/home/runner/work/FijiRelax/FijiRelax/lib/</argLine>
              </configuration>
	        </plugin>

I did that because I was stuck with the impossibility to change dynamically java.library.path in the mvn command activated by the action. I guess there should be more elegant ways to do this. However, that pom can be used both in github action and on a local config (reacts well with mvn install).
